name: Update Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Get all branches
        id: get_branches
        run: |
          git fetch --all
          branches=$(git branch -r | grep -v '\->' | grep -v 'main' | sed 's/origin\///')
          echo "Found branches:"
          echo "$branches"
          echo "::set-output name=branches::$branches"

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Update branches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for branch in $(echo "${{ steps.get_branches.outputs.branches }}"); do
            echo "Updating $branch"
            git checkout $branch
            git pull origin $branch

            # Verifica se há um merge em andamento e conclui ou aborta
            if [[ -f ".git/MERGE_HEAD" ]]; then
              echo "Completing or aborting the ongoing merge."
              git merge --abort || true
            fi

            # Realiza o merge com a main
            if git merge origin/main --no-commit --no-ff --allow-unrelated-histories; then
              echo "No conflicts in $branch, proceeding with merge."
              git merge --commit --no-ff --allow-unrelated-histories
              git push origin $branch
            else
              echo "Conflict detected in $branch. Creating a pull request."
              git merge --abort || true
              git checkout main
              git pull origin main
              git checkout -b pr-merge-main-into-$branch
              git merge $branch --allow-unrelated-histories || true
              git push origin pr-merge-main-into-$branch
              gh pr create --head pr-merge-main-into-$branch --base $branch --title "Merge main into $branch" --body "This PR resolves conflicts between main and $branch."
            fi
          done
