name: Update Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Get all branches
        id: get_branches
        run: |
          git fetch --all
          branches=$(git branch -r | grep -v '\->' | grep -v 'main' | sed 's/origin\///')
          echo "Found branches:"
          echo "$branches"
          echo "::set-output name=branches::$branches"

      - name: Update branches
        run: |
          for branch in $(echo "${{ steps.get_branches.outputs.branches }}"); do
            git checkout $branch
            git merge origin/main || {
              echo "Conflict detected in $branch. Creating a pull request."
              git checkout main
              git checkout -b pr-merge-main-into-$branch
              git push origin pr-merge-main-into-$branch
              gh pr create --head pr-merge-main-into-$branch --base $branch --title "Merge main into $branch" --body "This PR resolves conflicts between main and $branch."
            }
            git push origin $branch || true
          done

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
