name: Update branches on commit to base

on:
  push:
    branches:
      - base

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v2
        with:
          ref: base

      - name: Fetch all branches
        run: git fetch --all

      - name: Iterate over other branches
        run: |
          for branch in $(git branch -r | grep -v '->' | grep -v 'base'); do
            branch_name=$(echo "$branch" | sed 's/origin\///')
            git checkout -B $branch_name $branch
            git merge origin/base --no-commit
            if [ $? -ne 0 ]; then
              git checkout -b resolve-conflict-$branch_name
              git commit -am "Resolve conflict"
              git push origin resolve-conflict-$branch_name
              # Create pull request
              # Example: hub pull-request -b $branch_name -h resolve-conflict-$branch_name
            else
              git commit -am "Merge from base"
              git push origin $branch_name
            fi
          done
